Include `Result` in `UnwrapError`
dbrgn/result pull request #35
Opened 2020-10-11 14:22 UTC by PhilipTrauner

This PR should merely be regarded as a suggestion and to discuss if this change would be desirable.

Including the result when constructing `UnwrapError` enables using Python's exception semantics in a similar fashion to Rust's `?` early return operator. 

<details open>
<summary>Example usage</summary>

<p>Performing a series of failable operations, while obtaining context about the failed operation upon unwrapping. This is different from using regular exceptions in that the error type (which could also be an actual <code>Exception</code> or a <code>Union</code> type) is part of the function signature.</p>

```python
from result import Result, Ok, Err, UnwrapError
from dataclasses import dataclass

@dataclass
class ComputationError:
    number: int

def compute(number: int) -> Result[int, ComputationError]:
    return Ok(number) if number < 10 else Err(ComputationError(number))

a = compute(9)
b = compute(10)

try:
    c = a.unwrap() + b.unwrap()
except UnwrapError as e:
    print(f"Computation exception occurred: unexpected value '{e.result.value.number}'")
```

</details>

I've been using my fork of this library in various projects, and I've so far applied this pattern extensively.  
I'd appreciate if this change could be mainlined, as I don't really want to keep my fork around 😄.

2020-10-12 07:36 UTC, dbrgn approved these changes
Thanks @PhilipTrauner, that looks like a simple but nice addition to me. @francium do you agree?

2020-10-12 07:37 UTC, dbrgn commented
Ah, regarding the failing CI, it would be nice if you could add a test for this (could be very similar to your usage example).

2020-10-12 09:39 UTC, PhilipTrauner commented
> Ah, regarding the failing CI, it would be nice if you could add a test for this (could be very similar to your usage example).

Gladly! 😄 (https://github.com/dbrgn/result/pull/35/commits/0c528554111a0deccbbfcdf9b838de85d6ce263f)

2020-10-12 14:02 UTC, francium commented
This is interesting. Thanks for bring this up @PhilipTrauner .

2020-10-12 14:08 UTC, francium requested changes

2020-10-12 14:08 UTC, francium commented on result/tests.py
> +    assert e.value.result is n
Ideally we'd put a single standalone test to assert the result is in the exception so we don't have to repeat it in multiple tests

2020-10-12 14:17 UTC, francium commented
I guess the intended usage is something like this,
```python
T = TypeVar("T")
Except = Generic[T]

class MathError:
    def __init__(self, msg: str) -> None:        self.msg = msg
    def __repr__(self) -> str:        return 'MathError(msg="{}")'.format(self.msg)

def failing() -> Result[int, MathError]:
    n = Err(MathError('floating point error'))
    return n

def add_1_to(n: int) -> Except[int]:
    r = Ok(n).unwrap() + failing().unwrap()
    return r

def some_function_using_result() -> None:
    try:
        add_1_to(3)
    except UnwrapError as ue:
        print('Failed to perform add:', ue.result)

some_function_using_result()
```

Note that I've tried to define a `Except` generic type for the purpose of creating self-documenting code. Idea being you indicate to the user using this type that the function will throw an error if something goes wrong, but the error is of type UnwrapError containing the Result.
I can't see any other way of encoding it nicely like Rust does with the `?` or Zig does with `anyerror!u32` (1).
It doesn't actually work, not sure with exact thing I need to specify to make the generic `Except` be acceptable to the typechecker. But just an idea, maybe it's worth looking into, maybe not?

(1) https://ziglang.org/documentation/master/#Error-Union-Type and https://ziglang.org/documentation/master/#while-with-Error-Unions

2020-10-12 16:19 UTC, francium approved these changes

2020-10-12 16:20 UTC, francium commented
Look okay to me.

2020-10-13 07:43 UTC, dbrgn approved these changes
Thanks!

2020-10-13 07:43 UTC, merged